# Generated by Django 3.2.4 on 2021-06-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
