# Generated by Django 3.2.4 on 2021-06-23 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_produit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='produit')),
                ('image2', models.ImageField(upload_to='produit')),
                ('image3', models.ImageField(upload_to='produit')),
                ('image4', models.ImageField(upload_to='produit')),
                ('image5', models.ImageField(upload_to='produit')),
                ('image6', models.ImageField(upload_to='produit')),
                ('image7', models.ImageField(upload_to='produit')),
                ('image8', models.ImageField(upload_to='produit')),
                ('image9', models.ImageField(upload_to='produit')),
                ('image10', models.ImageField(upload_to='produit')),
            ],
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.album'),
        ),
    ]
