# Generated by Django 3.2.4 on 2021-06-23 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0003_auto_20210623_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='album',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='album',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='album',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='album',
            name='image9',
        ),
    ]
