# Generated by Django 3.2.4 on 2021-06-23 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0005_auto_20210623_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='image',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
