# Generated by Django 3.2.4 on 2021-06-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0006_auto_20210623_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image1', models.ImageField(upload_to='produit')),
                ('image2', models.ImageField(upload_to='produit')),
                ('image3', models.ImageField(upload_to='produit')),
                ('image4', models.ImageField(upload_to='produit')),
                ('image5', models.ImageField(upload_to='produit')),
                ('image6', models.ImageField(upload_to='produit')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Album',
            },
        ),
    ]
