# Generated by Django 3.2.4 on 2021-06-23 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0009_auto_20210623_0620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name': 'Categorie', 'verbose_name_plural': 'Categorie'},
        ),
        migrations.AlterField(
            model_name='album',
            name='image1',
            field=models.ImageField(upload_to='produit/media'),
        ),
        migrations.AlterField(
            model_name='album',
            name='image2',
            field=models.ImageField(upload_to='produit/media'),
        ),
        migrations.AlterField(
            model_name='album',
            name='image3',
            field=models.ImageField(upload_to='produit/media'),
        ),
        migrations.AlterField(
            model_name='album',
            name='image4',
            field=models.ImageField(upload_to='produit/media'),
        ),
        migrations.AlterField(
            model_name='album',
            name='image5',
            field=models.ImageField(upload_to='produit/media'),
        ),
        migrations.AlterField(
            model_name='album',
            name='image6',
            field=models.ImageField(upload_to='produit/media'),
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.produit')),
            ],
            options={
                'verbose_name': 'Moto',
                'verbose_name_plural': 'Moto',
            },
        ),
    ]
