# Generated by Django 3.2.4 on 2021-06-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0011_auto_20210623_1154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produit_par_categorie',
        ),
    ]
