# Generated by Django 3.2.4 on 2021-06-24 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0015_auto_20210624_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('position', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Vendeur',
                'verbose_name_plural': 'Vendeur',
            },
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Produit', 'verbose_name_plural': 'Produit'},
        ),
        migrations.AddField(
            model_name='produit',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='sold_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendeur_produit', to='produit.vendeur'),
        ),
    ]
