# Generated by Django 3.2.4 on 2021-06-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0016_auto_20210624_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendeur',
            old_name='position',
            new_name='lieu',
        ),
    ]
