# Generated by Django 3.2.4 on 2021-06-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0017_rename_position_vendeur_lieu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='slug',
        ),
    ]
