# Generated by Django 3.2.4 on 2021-06-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0019_auto_20210624_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='slug',
            field=models.CharField(default=models.CharField(max_length=200, unique=True), max_length=200),
        ),
        migrations.AlterField(
            model_name='album',
            name='image1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='image2',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='image3',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='image4',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='image5',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
