# Generated by Django 3.2.4 on 2021-06-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0020_auto_20210625_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
