# Generated by Django 3.2.4 on 2021-06-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0021_auto_20210625_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='in_home',
            field=models.BooleanField(default=False),
        ),
    ]
