# Generated by Django 3.2.4 on 2021-06-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0022_produit_in_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='price',
            new_name='new_price',
        ),
        migrations.AddField(
            model_name='produit',
            name='old_price',
            field=models.IntegerField(default=0),
        ),
    ]
