# Generated by Django 3.2.4 on 2021-06-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0023_auto_20210629_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendeur',
            name='contact',
            field=models.CharField(max_length=200),
        ),
    ]
