# Generated by Django 3.2.4 on 2021-06-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0024_alter_vendeur_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeur',
            name='whatsap',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
