# Generated by Django 3.2.4 on 2021-06-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0026_auto_20210630_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='in_home',
            field=models.BooleanField(default=True),
        ),
    ]
