# Generated by Django 3.2.4 on 2021-10-31 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0027_alter_produit_in_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='album',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='album',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='album',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='album',
            name='image5',
        ),
    ]
