# Generated by Django 3.2.4 on 2021-10-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0028_auto_20211031_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image1',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='album',
            name='image2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='album',
            name='image3',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='album',
            name='image4',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='album',
            name='image5',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
